apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJWbmxoWTJobGMyeGhkaTFGY21GemRHOTJPbWRvY0Y5MU5uTmpaRXRvUWpKSFRIZE5XR3BuYVdaamJsaG5jek5FTjJoTlJXWXdiMWhNVUVvPSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
